#
# File: https://github.com/data-engineering-helpers/mds-in-a-box/tree/main/unitycatalog-playground/docker-compose.yaml
#
# See also:
# * SeaweedFS: https://github.com/data-engineering-helpers/mds-in-a-box/tree/main/unitycatalog-playground/docker-compose-seaweedfs.yaml
#
# Inspired by:
# * For Unity Catalog (UC):
#   * Pristine UC: https://github.com/unitycatalog/unitycatalog/blob/main/compose.yaml
#   * Lakehouse at home: https://github.com/lisancao/lakehouse-at-home/blob/master/docker-compose-unity-catalog.yml
#
# unitycatalog image:
# * On Docker Hub: https://hub.docker.com/r/unitycatalog/unitycatalog
# * Dockerfile on GitHub: https://github.com/unitycatalog/unitycatalog/blob/main/Dockerfile
#
# unitycatalog-ui image:
# * On Docker Hub: https://hub.docker.com/r/unitycatalog/unitycatalog-ui
# * Dockerfile on GitHub: https://github.com/unitycatalog/unitycatalog/blob/main/ui/Dockerfile
#
name: lakehouse-uc

services:

  unity-catalog:
    image: unitycatalog/unitycatalog:main
    # hostname: unity-catalog
    container_name: unity-catalog
    ports:
      # REST API + Iceberg REST Catalog endpoint
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx2g
    command: 'bin/start-uc-server'
    volumes:
      - type: bind
        source: ./etc/conf/server.properties
        target: /home/unitycatalog/etc/conf/server.properties
      # todo add a long-term database here since it can 
      # trip up the process when spinning the environment back up.
      #- type: volume
      #  source: uc-data
      #  target: /home/unitycatalog/etc/data
      #- type: volume
      #  source: uc-db
      #  target: /home/unitycatalog/etc/db
      #- type: volume
      #  source: uc-logs
      #  target: /home/unitycatalog/etc/logs
    networks:
      - lhnet

  unity-catalog-ui:
    image: unitycatalog/unitycatalog-ui:main
    container_name: unity-catalog-ui
    ports:
      - "3000:3000"
    environment:
      - UC_API_URL=http://unity-catalog:8080
    command: 'yarn start'
    depends_on:
      - unity-catalog
    networks:
      - lhnet

volumes:
  uc-data:
    driver: local
  uc-db:
    driver: local
  uc-logs:
    driver: local

networks:
  lhnet:
    driver: bridge
