#
# File: https://github.com/data-engineering-helpers/mds-in-a-box/tree/main/unitycatalog-playground/Makefile
#

container-start: ## Start Docker containers
	@docker compose up -d

container-stop: ## Stop Docker containers
	@docker compose down


